import carouselImg1 from "../images/carouselImg1.jpg";
import carouselImg2 from "../images/carouselImg2.jpeg";
import carouselImg3 from "../images/carouselImg3.jpg";
import areaImg1 from "../images/areaImg1.png";
import areaImg2 from "../images/areaImg2.png";
import areaImg3 from "../images/areaImg3.png";
import areaImg4 from "../images/areaImg4.png";
import woman1 from "../images/woman1.jpg";
import woman2 from "../images/woman2.jpg";
import woman3 from "../images/woman3.jpg";
import woman4 from "../images/woman4.jpg";
import growingImg from "../images/growingImg.png"
import News1 from "../images/News1.jpeg";
import News2 from "../images/News2.jpg";
import News3 from "../images/News3.jpg";
import News4 from "../images/News4.jpeg";
import News5 from "../images/News5.jpeg";
import News6 from "../images/News6.jpg";
import News7 from "../images/News7.jpeg";
import News8 from "../images/News8.png";
import News9 from "../images/News9.jpg";
import partner1 from "../images/partner1.jpg";
import partner2 from "../images/partner2.png";
import partner3 from "../images/partner3.png";
import partner4 from "../images/partner4.jpg";
import partner5 from "../images/partner5.png";
import partner6 from "../images/partner6.png";
import partner7 from "../images/partner7.jpg";
import partner8 from "../images/partner8.png";
import partner9 from "../images/partner9.png";
import partner10 from "../images/partner10.png";
import partner11 from "../images/partner11.jpg";
import partner12 from "../images/partner12.png";
import partner13 from "../images/partner13.jpg";
import partner14 from "../images/partner14.png";
import partner15 from "../images/partner15.png";



export { areaImg1,areaImg2,areaImg3,areaImg4,woman1,woman2,woman3,woman4,growingImg,News1,News2,News3,News4,News5,News6,News7,News8,News9 ,partner1,partner2,partner3,partner4,partner5,partner6,partner7,partner8,partner9,partner10,partner11,partner12,partner13,partner14,partner15,carouselImg1,carouselImg2,carouselImg3};
